"""add llm and finding columns to review_runs

Revision ID: 37e292134510
Revises: 75a08c2847ca
Create Date: 2026-09-30 21:25:02.549964

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37e292134510"
down_revision: str | Sequence[str] | None = "75a08c2847ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_runs",
        sa.Column("finding_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column(
        "review_runs",
        sa.Column("raw_finding_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column("review_runs", sa.Column("prompt_tokens", sa.Integer(), nullable=True))
    op.add_column("review_runs", sa.Column("completion_tokens", sa.Integer(), nullable=True))
    op.add_column("review_runs", sa.Column("model", sa.Text(), nullable=True))
    op.add_column("review_runs", sa.Column("diff_chars", sa.Integer(), nullable=True))
    op.add_column(
        "review_runs",
        sa.Column("diff_truncated", sa.Boolean(), server_default=sa.text("false"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_runs", "diff_truncated")
    op.drop_column("review_runs", "diff_chars")
    op.drop_column("review_runs", "model")
    op.drop_column("review_runs", "completion_tokens")
    op.drop_column("review_runs", "prompt_tokens")
    op.drop_column("review_runs", "raw_finding_count")
    op.drop_column("review_runs", "finding_count")
    # ### end Alembic commands ###
